---
title: "p8105_hw5_ms6358.Rmd"
output: github_document
---

```{r}
library(tidyverse)
```

## Create a city_state variable

```{r}
homicide_df = 
  read.csv("./homicide-data.csv", na = c("","unknown")) %>%
  mutate(
    city_state = str_c(city,state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved"
    )) %>%
  relocate(city_state) %>%
  filter(city_state != "TulsaAL")
```

##  Use the prop.test function to estimate the proportion of homicides that are unsolved

```{r}
baltimore_df =
  homicide_df %>%
  filter(city_state == "BaltimoreMD")

baltimore_summary =
  baltimore_df %>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

baltimore_test = 
  prop.test(
  x = baltimore_summary %>% pull(unsolved),
  n = baltimore_summary %>% pull(n)
)

baltimore_test %>%
  broom::tidy()
```

## Run prop.test for each of the cities

```{r}
prop_test_function = function(city_df) {
  
city_summary =
  city_df %>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

city_test = 
  prop.test(
  x = city_summary %>% pull(unsolved),
  n = city_summary %>% pull(n)
)

return(city_test)
}

results_df = 
  homicide_df %>%
  nest(data = uid:resolution) %>%
  mutate(
    test_results = map(data, prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  ) %>%
  select(city_state, tidy_results) %>%
  unnest(tidy_results) %>%
  select(city_state, estimate, starts_with("conf"))
```

```{r}
results_df %>%
  mutate(city_state = fct_reorder(city_state, estimate)) %>%
  ggplot(aex(x = city_state, y = estimate)) +
  geom_point() +
```